// Fake data used by the mock API layer (Phase 1) so the frontend runs
// before the Laravel backend exists. Swap to the real backend by setting
// REACT_APP_USE_MOCK=false (see src/api/client.js).

export const CATEGORIES = [
  "Electrician",
  "Plumber",
  "Carpenter",
  "AC Technician",
  "Mechanic",
  "Painter",
  "Laborer",
];

export const CITIES = ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Hyderabad"];

// Demo workers — mirrors the mobile app's seed list so demos don't look empty.
export const MOCK_WORKERS = [
  {
    id: 101,
    full_name: "Imran Ali",
    city: "Karachi",
    photo_path: null,
    category: "Electrician",
    bio: "Certified electrician with 8 years of experience in residential and commercial wiring.",
    skills: ["Wiring", "Fan installation", "Circuit repair", "UPS setup"],
    experience_years: 8,
    hourly_rate: 800,
    service_area: "Gulshan-e-Iqbal",
    is_available: true,
    is_verified: true,
    average_rating: 4.7,
    total_reviews: 34,
    total_jobs_done: 120,
  },
  {
    id: 102,
    full_name: "Bilal Ahmed",
    city: "Karachi",
    photo_path: null,
    category: "Plumber",
    bio: "Expert plumber for leakages, water tanks, and bathroom fittings.",
    skills: ["Leak repair", "Pipe fitting", "Tank cleaning", "Geyser install"],
    experience_years: 6,
    hourly_rate: 700,
    service_area: "North Nazimabad",
    is_available: true,
    is_verified: true,
    average_rating: 4.5,
    total_reviews: 21,
    total_jobs_done: 85,
  },
  {
    id: 103,
    full_name: "Saeed Khan",
    city: "Lahore",
    photo_path: null,
    category: "Carpenter",
    bio: "Custom furniture, door repair, and woodwork specialist.",
    skills: ["Furniture", "Door repair", "Polishing", "Cabinets"],
    experience_years: 10,
    hourly_rate: 900,
    service_area: "Johar Town",
    is_available: false,
    is_verified: true,
    average_rating: 4.8,
    total_reviews: 47,
    total_jobs_done: 160,
  },
  {
    id: 104,
    full_name: "Naveed Iqbal",
    city: "Karachi",
    photo_path: null,
    category: "AC Technician",
    bio: "AC installation, gas refilling, and servicing for all brands.",
    skills: ["AC service", "Gas refill", "Installation", "Cooling repair"],
    experience_years: 5,
    hourly_rate: 1000,
    service_area: "DHA Phase 5",
    is_available: true,
    is_verified: false,
    average_rating: 4.3,
    total_reviews: 12,
    total_jobs_done: 40,
  },
  {
    id: 105,
    full_name: "Asif Raza",
    city: "Islamabad",
    photo_path: null,
    category: "Mechanic",
    bio: "Home car service, battery, and engine diagnostics.",
    skills: ["Engine", "Battery", "Oil change", "Diagnostics"],
    experience_years: 7,
    hourly_rate: 1200,
    service_area: "F-11",
    is_available: true,
    is_verified: true,
    average_rating: 4.6,
    total_reviews: 28,
    total_jobs_done: 95,
  },
  {
    id: 106,
    full_name: "Kamran Shah",
    city: "Karachi",
    photo_path: null,
    category: "Painter",
    bio: "Interior and exterior painting with clean, on-time work.",
    skills: ["Wall paint", "Texture", "Waterproofing", "Ceiling"],
    experience_years: 9,
    hourly_rate: 600,
    service_area: "Malir",
    is_available: true,
    is_verified: true,
    average_rating: 4.4,
    total_reviews: 19,
    total_jobs_done: 70,
  },
  {
    id: 107,
    full_name: "Rashid Mehmood",
    city: "Rawalpindi",
    photo_path: null,
    category: "Laborer",
    bio: "General labor, shifting, and loading work. Reliable and punctual.",
    skills: ["Shifting", "Loading", "Cleaning", "Digging"],
    experience_years: 4,
    hourly_rate: 500,
    service_area: "Saddar",
    is_available: true,
    is_verified: false,
    average_rating: 4.1,
    total_reviews: 8,
    total_jobs_done: 30,
  },
  {
    id: 108,
    full_name: "Faisal Nadeem",
    city: "Lahore",
    photo_path: null,
    category: "Electrician",
    bio: "Quick response electrician for emergencies and installations.",
    skills: ["Emergency repair", "Wiring", "MCB", "Lighting"],
    experience_years: 6,
    hourly_rate: 750,
    service_area: "Model Town",
    is_available: true,
    is_verified: true,
    average_rating: 4.5,
    total_reviews: 25,
    total_jobs_done: 88,
  },
];

export const MOCK_REVIEWS = [
  {
    id: 1,
    worker_id: 101,
    customer_name: "Ahmed S.",
    rating: 5,
    comment: "Very professional, fixed the wiring quickly.",
    tags: ["On time", "Professional"],
    created_at: "2026-06-10",
  },
  {
    id: 2,
    worker_id: 101,
    customer_name: "Sana K.",
    rating: 4,
    comment: "Good work, slightly late but polite.",
    tags: ["Skilled"],
    created_at: "2026-06-15",
  },
  {
    id: 3,
    worker_id: 102,
    customer_name: "Usman R.",
    rating: 5,
    comment: "Fixed a bad leak, fair price.",
    tags: ["Fair price", "On time"],
    created_at: "2026-06-20",
  },
];
